# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: multhetizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'multhetizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11multhetizer.proto\x12\x0emulthetizer.v1\"\'\n\x04Note\x12\r\n\x05pitch\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\"+\n\x0c\x43onfirmation\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2F\n\x04Play\x12>\n\x08SendNote\x12\x14.multhetizer.v1.Note\x1a\x1c.multhetizer.v1.Confirmationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multhetizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=37
  _globals['_NOTE']._serialized_end=76
  _globals['_CONFIRMATION']._serialized_start=78
  _globals['_CONFIRMATION']._serialized_end=121
  _globals['_PLAY']._serialized_start=123
  _globals['_PLAY']._serialized_end=193
# @@protoc_insertion_point(module_scope)
